import { useState } from 'react';
import DropZone from './components/DropZone';
import ProgressBar from './components/ProgressBar';
import ResultCard from './components/ResultCard';
import { useAnalyzer } from './hooks/useAnalyzer';

function Header() {
  return (
    <header style={{
      borderBottom: '1px solid rgba(255,255,255,0.06)',
      padding: '18px 40px',
      display: 'flex', alignItems: 'center', justifyContent: 'space-between',
      backdropFilter: 'blur(10px)',
      position: 'sticky', top: 0, zIndex: 10,
      background: 'rgba(10,10,15,0.85)'
    }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
        <div style={{
          width: 34, height: 34, borderRadius: 10,
          background: 'linear-gradient(135deg, #6c63ff, #a78bfa)',
          display: 'flex', alignItems: 'center', justifyContent: 'center',
          fontSize: 16
        }}>📄</div>
        <span style={{ fontSize: 16, fontWeight: 700, color: '#f0f0f8', letterSpacing: '-0.02em' }}>DocAI</span>
      </div>
      <div style={{ display: 'flex', gap: 8 }}>
        {['PDF', 'DOCX', 'IMAGE'].map(t => (
          <span key={t} style={{
            fontSize: 11, fontWeight: 600, padding: '3px 9px', borderRadius: 6,
            background: 'rgba(108,99,255,0.1)', color: '#8b84ff',
            border: '1px solid rgba(108,99,255,0.2)', letterSpacing: '0.04em'
          }}>{t}</span>
        ))}
      </div>
    </header>
  );
}

function HistoryPanel({ history }) {
  if (!history.length) return null;
  return (
    <div style={{
      background: 'rgba(255,255,255,0.02)', borderRadius: 14,
      border: '1px solid rgba(255,255,255,0.06)', padding: '16px 20px', marginTop: 16
    }}>
      <p style={{ fontSize: 12, fontWeight: 600, color: '#8b8ba0', textTransform: 'uppercase', letterSpacing: '0.07em', marginBottom: 12 }}>
        Recent
      </p>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
        {history.map((h, i) => (
          <div key={i} style={{
            display: 'flex', alignItems: 'center', justifyContent: 'space-between',
            padding: '8px 0',
            borderBottom: i < history.length - 1 ? '1px solid rgba(255,255,255,0.05)' : 'none'
          }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
              <span style={{ fontSize: 14 }}>📄</span>
              <div>
                <p style={{ fontSize: 13, color: '#d0d0e8', fontWeight: 500 }}>{h.file}</p>
                <p style={{ fontSize: 11, color: '#55556a' }}>{h.ts.toLocaleTimeString()}</p>
              </div>
            </div>
            <span style={{
              fontSize: 11, padding: '2px 8px', borderRadius: 6, fontWeight: 600,
              background: h.result.sentiment === 'Positive' ? 'rgba(34,197,94,0.1)' :
                          h.result.sentiment === 'Negative' ? 'rgba(239,68,68,0.1)' : 'rgba(108,99,255,0.1)',
              color: h.result.sentiment === 'Positive' ? '#22c55e' :
                     h.result.sentiment === 'Negative' ? '#ef4444' : '#8b84ff'
            }}>{h.result.sentiment}</span>
          </div>
        ))}
      </div>
    </div>
  );
}

function HeroSection() {
  return (
    <div style={{ textAlign: 'center', marginBottom: 52, padding: '0 16px' }}>
      
      <h1 style={{
        fontSize: 'clamp(32px, 5vw, 54px)', fontWeight: 800, lineHeight: 1.15,
        background: 'linear-gradient(135deg, #f0f0f8 0%, #8b84ff 50%, #a78bfa 100%)',
        WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent',
        backgroundClip: 'text', marginBottom: 18, letterSpacing: '-0.03em'
      }}>
        Understand any document<br />in seconds
      </h1>

      <p style={{ fontSize: 17, color: '#8b8ba0', maxWidth: 520, margin: '0 auto', lineHeight: 1.7 }}>
        Upload a PDF, Word document, or image and get an instant AI-powered summary,
        named entities, sentiment analysis, and more.
      </p>
    </div>
  );
}

function FeatureRow() {
  const features = [
    { icon: '🧠', title: 'AI Summary', desc: 'Concise 2-3 sentence overview generated by Claude' },
    { icon: '🔍', title: 'Entity Extraction', desc: 'Names, orgs, dates, amounts, locations' },
    { icon: '💬', title: 'Sentiment Analysis', desc: 'Positive, Neutral, or Negative with a confidence score' },
    { icon: '📊', title: 'Document Insights', desc: 'Word count, reading time, type classification' },
  ];
  return (
    <div style={{
      display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))',
      gap: 14, marginTop: 40
    }}>
      {features.map(f => (
        <div key={f.title} style={{
          background: 'rgba(255,255,255,0.025)', borderRadius: 14,
          border: '1px solid rgba(255,255,255,0.06)', padding: '18px 16px',
          transition: 'border-color 0.2s'
        }}>
          <span style={{ fontSize: 22, display: 'block', marginBottom: 10 }}>{f.icon}</span>
          <p style={{ fontSize: 13, fontWeight: 600, color: '#d0d0e8', marginBottom: 5 }}>{f.title}</p>
          <p style={{ fontSize: 12, color: '#55556a', lineHeight: 1.5 }}>{f.desc}</p>
        </div>
      ))}
    </div>
  );
}

export default function App() {
  const { status, result, error, progress, history, analyze, reset } = useAnalyzer();
  const [selectedFile, setSelectedFile] = useState(null);

  const handleFile = (file) => {
    setSelectedFile(file);
    analyze(file);
  };

  const handleReset = () => {
    reset();
    setSelectedFile(null);
  };

  const isProcessing = status === 'uploading' || status === 'analyzing';

  return (
    <div style={{ minHeight: '100vh', background: 'var(--bg)' }}>
      <Header />

      {/* Background decoration */}
      <div style={{ position: 'fixed', inset: 0, pointerEvents: 'none', overflow: 'hidden', zIndex: 0 }}>
        <div style={{
          position: 'absolute', top: '-20%', left: '50%', transform: 'translateX(-50%)',
          width: 700, height: 700, borderRadius: '50%',
          background: 'radial-gradient(circle, rgba(108,99,255,0.08) 0%, transparent 70%)'
        }} />
      </div>

      <main style={{ position: 'relative', zIndex: 1, maxWidth: 820, margin: '0 auto', padding: '60px 24px 80px' }}>

        {/* ── IDLE: show hero + dropzone ── */}
        {status === 'idle' && (
          <>
            <HeroSection />
            <DropZone onFile={handleFile} disabled={isProcessing} />
            <HistoryPanel history={history} />
            <FeatureRow />
          </>
        )}

        {/* ── PROCESSING ── */}
        {isProcessing && (
          <div style={{ marginTop: 60 }}>
            <div style={{ textAlign: 'center', marginBottom: 40 }}>
              <p style={{ fontSize: 15, color: '#8b8ba0', marginBottom: 8 }}>Analysing</p>
              <p style={{ fontSize: 20, fontWeight: 700, color: '#f0f0f8' }}>{selectedFile?.name}</p>
            </div>
            <ProgressBar status={status} progress={progress} />

            <div style={{
              marginTop: 32, display: 'grid',
              gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))', gap: 12
            }}>
              {['Extracting text', 'Identifying entities', 'Generating summary', 'Analysing sentiment'].map((step, i) => (
                <div key={step} style={{
                  background: 'rgba(255,255,255,0.03)', borderRadius: 12,
                  border: '1px solid rgba(255,255,255,0.07)',
                  padding: '14px 16px', display: 'flex', alignItems: 'center', gap: 10
                }}>
                  <div style={{
                    width: 8, height: 8, borderRadius: '50%',
                    background: progress > (i + 1) * 20 ? '#22c55e' : progress > i * 20 ? '#6c63ff' : 'rgba(255,255,255,0.15)',
                    transition: 'background 0.4s'
                  }} />
                  <span style={{ fontSize: 13, color: progress > i * 20 ? '#d0d0e8' : '#55556a', transition: 'color 0.4s' }}>
                    {step}
                  </span>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* ── DONE ── */}
        {status === 'done' && result && (
          <ResultCard result={result} onReset={handleReset} />
        )}

        {/* ── ERROR ── */}
        {status === 'error' && (
          <div style={{ marginTop: 60, textAlign: 'center' }}>
            <div style={{
              background: 'rgba(239,68,68,0.08)', border: '1px solid rgba(239,68,68,0.2)',
              borderRadius: 16, padding: '40px 32px', maxWidth: 480, margin: '0 auto'
            }}>
              <span style={{ fontSize: 48, display: 'block', marginBottom: 16 }}>⚠️</span>
              <h3 style={{ fontSize: 18, fontWeight: 700, color: '#f0f0f8', marginBottom: 10 }}>Analysis Failed</h3>
              <p style={{ fontSize: 14, color: '#8b8ba0', marginBottom: 24, lineHeight: 1.6 }}>{error}</p>
              <button onClick={handleReset} style={{
                padding: '10px 24px', borderRadius: 10, fontSize: 14, cursor: 'pointer',
                background: 'rgba(239,68,68,0.15)', color: '#ef4444',
                border: '1px solid rgba(239,68,68,0.3)', fontWeight: 600
              }}>Try Again</button>
            </div>
          </div>
        )}
      </main>
    </div>
  );
}
